//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siemens.Automation.bfapicmx_csharpsamplex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siemens.Automation.bfapicmx_csharpsamplex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddUser.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advise.
        /// </summary>
        public static string Advise2PCell {
            get {
                return ResourceManager.GetString("Advise2PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advise4Object.
        /// </summary>
        public static string Advise4Object {
            get {
                return ResourceManager.GetString("Advise4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advise4SIS.
        /// </summary>
        public static string Advise4SIS {
            get {
                return ResourceManager.GetString("Advise4SIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUp.
        /// </summary>
        public static string BackUp {
            get {
                return ResourceManager.GetString("BackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string BatchMLPath {
            get {
                return ResourceManager.GetString("BatchMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelRefresh.
        /// </summary>
        public static string CancelRefresh {
            get {
                return ResourceManager.GetString("CancelRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChainBatch2Batch.
        /// </summary>
        public static string ChainBatch2Batch {
            get {
                return ResourceManager.GetString("ChainBatch2Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearLock4Object.
        /// </summary>
        public static string ClearLock4Object {
            get {
                return ResourceManager.GetString("ClearLock4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyBatch.
        /// </summary>
        public static string CopyBatch {
            get {
                return ResourceManager.GetString("CopyBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyFormula.
        /// </summary>
        public static string CopyFormula {
            get {
                return ResourceManager.GetString("CopyFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyOrder.
        /// </summary>
        public static string CopyOrder {
            get {
                return ResourceManager.GetString("CopyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyRecipe.
        /// </summary>
        public static string CopyRecipe {
            get {
                return ResourceManager.GetString("CopyRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBatch.
        /// </summary>
        public static string CreateBatch {
            get {
                return ResourceManager.GetString("CreateBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateFormula.
        /// </summary>
        public static string CreateFormula {
            get {
                return ResourceManager.GetString("CreateFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateFormulaCat.
        /// </summary>
        public static string CreateFormulaCat {
            get {
                return ResourceManager.GetString("CreateFormulaCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateLibrary.
        /// </summary>
        public static string CreateLibrary {
            get {
                return ResourceManager.GetString("CreateLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateManyMaterials.
        /// </summary>
        public static string CreateManyMaterials {
            get {
                return ResourceManager.GetString("CreateManyMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateMaterial.
        /// </summary>
        public static string CreateMaterial {
            get {
                return ResourceManager.GetString("CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateOrder.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateOrderCat.
        /// </summary>
        public static string CreateOrderCat {
            get {
                return ResourceManager.GetString("CreateOrderCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateQuality.
        /// </summary>
        public static string CreateQuality {
            get {
                return ResourceManager.GetString("CreateQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRecipe.
        /// </summary>
        public static string CreateRecipe {
            get {
                return ResourceManager.GetString("CreateRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSubfolder.
        /// </summary>
        public static string CreateSubfolder {
            get {
                return ResourceManager.GetString("CreateSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteBatch.
        /// </summary>
        public static string DeleteBatch {
            get {
                return ResourceManager.GetString("DeleteBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFormula.
        /// </summary>
        public static string DeleteFormula {
            get {
                return ResourceManager.GetString("DeleteFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteFormulaCat.
        /// </summary>
        public static string DeleteFormulaCat {
            get {
                return ResourceManager.GetString("DeleteFormulaCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteLibrary.
        /// </summary>
        public static string DeleteLibrary {
            get {
                return ResourceManager.GetString("DeleteLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteMaterial.
        /// </summary>
        public static string DeleteMaterial {
            get {
                return ResourceManager.GetString("DeleteMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteOrder.
        /// </summary>
        public static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteOrderCat.
        /// </summary>
        public static string DeleteOrderCat {
            get {
                return ResourceManager.GetString("DeleteOrderCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteQuality.
        /// </summary>
        public static string DeleteQuality {
            get {
                return ResourceManager.GetString("DeleteQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRecipe.
        /// </summary>
        public static string DeleteRecipe {
            get {
                return ResourceManager.GetString("DeleteRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteSubfolder.
        /// </summary>
        public static string DeleteSubfolder {
            get {
                return ResourceManager.GetString("DeleteSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisConnect.
        /// </summary>
        public static string DisConnect {
            get {
                return ResourceManager.GetString("DisConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecuteCommand.
        /// </summary>
        public static string ExecuteCommand {
            get {
                return ResourceManager.GetString("ExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllActiveXFERPhase4PCell.
        /// </summary>
        public static string GetAllActiveXFERPhase4PCell {
            get {
                return ResourceManager.GetString("GetAllActiveXFERPhase4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllBatches4Order.
        /// </summary>
        public static string GetAllBatches4Order {
            get {
                return ResourceManager.GetString("GetAllBatches4Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllChainedPredecessors4Batch.
        /// </summary>
        public static string GetAllChainedPredecessors4Batch {
            get {
                return ResourceManager.GetString("GetAllChainedPredecessors4Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllChainedSuccessors4Batch.
        /// </summary>
        public static string GetAllChainedSuccessors4Batch {
            get {
                return ResourceManager.GetString("GetAllChainedSuccessors4Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllChainRoots4PCell.
        /// </summary>
        public static string GetAllChainRoots4PCell {
            get {
                return ResourceManager.GetString("GetAllChainRoots4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllDataTypes4PCell.
        /// </summary>
        public static string GetAllDataTypes4PCell {
            get {
                return ResourceManager.GetString("GetAllDataTypes4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllEventDefinitions.
        /// </summary>
        public static string GetAllEventDefinitions {
            get {
                return ResourceManager.GetString("GetAllEventDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllFormulaCats4PCell.
        /// </summary>
        public static string GetAllFormulaCats4PCell {
            get {
                return ResourceManager.GetString("GetAllFormulaCats4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllFormulas4FormulaCat.
        /// </summary>
        public static string GetAllFormulas4FormulaCat {
            get {
                return ResourceManager.GetString("GetAllFormulas4FormulaCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllFormulas4MR.
        /// </summary>
        public static string GetAllFormulas4MR {
            get {
                return ResourceManager.GetString("GetAllFormulas4MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllFormulasOrMR4CreateBatch.
        /// </summary>
        public static string GetAllFormulasOrMR4CreateBatch {
            get {
                return ResourceManager.GetString("GetAllFormulasOrMR4CreateBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllLIB4PCell.
        /// </summary>
        public static string GetAllLIB4PCell {
            get {
                return ResourceManager.GetString("GetAllLIB4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllMaterials4PCell.
        /// </summary>
        public static string GetAllMaterials4PCell {
            get {
                return ResourceManager.GetString("GetAllMaterials4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllMR4PCell.
        /// </summary>
        public static string GetAllMR4PCell {
            get {
                return ResourceManager.GetString("GetAllMR4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllocations.
        /// </summary>
        public static string GetAllocations {
            get {
                return ResourceManager.GetString("GetAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllOrderCats4PCell.
        /// </summary>
        public static string GetAllOrderCats4PCell {
            get {
                return ResourceManager.GetString("GetAllOrderCats4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllOrders4OrderCat.
        /// </summary>
        public static string GetAllOrders4OrderCat {
            get {
                return ResourceManager.GetString("GetAllOrders4OrderCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPCells4Project.
        /// </summary>
        public static string GetAllPCells4Project {
            get {
                return ResourceManager.GetString("GetAllPCells4Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPhysicalUnits4PCell.
        /// </summary>
        public static string GetAllPhysicalUnits4PCell {
            get {
                return ResourceManager.GetString("GetAllPhysicalUnits4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPrintTemplates4PCell.
        /// </summary>
        public static string GetAllPrintTemplates4PCell {
            get {
                return ResourceManager.GetString("GetAllPrintTemplates4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllProjects.
        /// </summary>
        public static string GetAllProjects {
            get {
                return ResourceManager.GetString("GetAllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllQualities4Material.
        /// </summary>
        public static string GetAllQualities4Material {
            get {
                return ResourceManager.GetString("GetAllQualities4Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllSubfolders4PCell.
        /// </summary>
        public static string GetAllSubfolders4PCell {
            get {
                return ResourceManager.GetString("GetAllSubfolders4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllSubscriptions.
        /// </summary>
        public static string GetAllSubscriptions {
            get {
                return ResourceManager.GetString("GetAllSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUnitClasses4PCell.
        /// </summary>
        public static string GetAllUnitClasses4PCell {
            get {
                return ResourceManager.GetString("GetAllUnitClasses4PCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUnits.
        /// </summary>
        public static string GetAllUnits {
            get {
                return ResourceManager.GetString("GetAllUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUnits4UnitClass.
        /// </summary>
        public static string GetAllUnits4UnitClass {
            get {
                return ResourceManager.GetString("GetAllUnits4UnitClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAttribute4Object.
        /// </summary>
        public static string GetAttribute4Object {
            get {
                return ResourceManager.GetString("GetAttribute4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBatchSize.
        /// </summary>
        public static string GetBatchSize {
            get {
                return ResourceManager.GetString("GetBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBatchStartData.
        /// </summary>
        public static string GetBatchStartData {
            get {
                return ResourceManager.GetString("GetBatchStartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBatchState.
        /// </summary>
        public static string GetBatchState {
            get {
                return ResourceManager.GetString("GetBatchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetChangedBatches.
        /// </summary>
        public static string GetChangedBatches {
            get {
                return ResourceManager.GetString("GetChangedBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetChildren.
        /// </summary>
        public static string GetChildren {
            get {
                return ResourceManager.GetString("GetChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetErrorText.
        /// </summary>
        public static string GetErrorText {
            get {
                return ResourceManager.GetString("GetErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFormulaCat4MR.
        /// </summary>
        public static string GetFormulaCat4MR {
            get {
                return ResourceManager.GetString("GetFormulaCat4MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHistorical
        ///SISEvents.
        /// </summary>
        public static string GetHistoricalSISEvents4Batch {
            get {
                return ResourceManager.GetString("GetHistoricalSISEvents4Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHistoricalSISEvents4Unit.
        /// </summary>
        public static string GetHistoricalSISEvents4Unit {
            get {
                return ResourceManager.GetString("GetHistoricalSISEvents4Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLogBookObjects.
        /// </summary>
        public static string GetLogBookObjects {
            get {
                return ResourceManager.GetString("GetLogBookObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMaterialData.
        /// </summary>
        public static string GetMaterialData {
            get {
                return ResourceManager.GetString("GetMaterialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMR4Formula.
        /// </summary>
        public static string GetMR4Formula {
            get {
                return ResourceManager.GetString("GetMR4Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetObjectData.
        /// </summary>
        public static string GetObjectData {
            get {
                return ResourceManager.GetString("GetObjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetObjectHeader.
        /// </summary>
        public static string GetObjectHeader {
            get {
                return ResourceManager.GetString("GetObjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetObjectState.
        /// </summary>
        public static string GetObjectState {
            get {
                return ResourceManager.GetString("GetObjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetParameter.
        /// </summary>
        public static string GetParameter {
            get {
                return ResourceManager.GetString("GetParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetParent.
        /// </summary>
        public static string GetParent {
            get {
                return ResourceManager.GetString("GetParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductData4Object (Formula).
        /// </summary>
        public static string GetProductData4Formula {
            get {
                return ResourceManager.GetString("GetProductData4Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductData4Object (MR).
        /// </summary>
        public static string GetProductData4MR {
            get {
                return ResourceManager.GetString("GetProductData4MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductData4Object.
        /// </summary>
        public static string GetProductData4Object {
            get {
                return ResourceManager.GetString("GetProductData4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetQualityData.
        /// </summary>
        public static string GetQualityData {
            get {
                return ResourceManager.GetString("GetQualityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init.
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEqualHDL.
        /// </summary>
        public static string IsEqualHDL {
            get {
                return ResourceManager.GetString("IsEqualHDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMaterialReferenced.
        /// </summary>
        public static string IsMaterialReferenced {
            get {
                return ResourceManager.GetString("IsMaterialReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockObject.
        /// </summary>
        public static string LockObject {
            get {
                return ResourceManager.GetString("LockObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintObject.
        /// </summary>
        public static string PrintObject {
            get {
                return ResourceManager.GetString("PrintObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveUser.
        /// </summary>
        public static string RemoveUser {
            get {
                return ResourceManager.GetString("RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAdviseFilter.
        /// </summary>
        public static string SetAdviseFilter {
            get {
                return ResourceManager.GetString("SetAdviseFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAllocations.
        /// </summary>
        public static string SetAllocations {
            get {
                return ResourceManager.GetString("SetAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAttribute4Object.
        /// </summary>
        public static string SetAttribute4Object {
            get {
                return ResourceManager.GetString("SetAttribute4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBatchSize.
        /// </summary>
        public static string SetBatchSize {
            get {
                return ResourceManager.GetString("SetBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBatchStartData.
        /// </summary>
        public static string SetBatchStartData {
            get {
                return ResourceManager.GetString("SetBatchStartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBatchState.
        /// </summary>
        public static string SetBatchState {
            get {
                return ResourceManager.GetString("SetBatchState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetCurrentUser.
        /// </summary>
        public static string SetCurrentUser {
            get {
                return ResourceManager.GetString("SetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFormulaCat4MR.
        /// </summary>
        public static string SetFormulaCat4MR {
            get {
                return ResourceManager.GetString("SetFormulaCat4MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetManyParameters.
        /// </summary>
        public static string SetManyParameters {
            get {
                return ResourceManager.GetString("SetManyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMaterialData.
        /// </summary>
        public static string SetMaterialData {
            get {
                return ResourceManager.GetString("SetMaterialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMR4Formula.
        /// </summary>
        public static string SetMR4Formula {
            get {
                return ResourceManager.GetString("SetMR4Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetObjectState.
        /// </summary>
        public static string SetObjectState {
            get {
                return ResourceManager.GetString("SetObjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetParameter.
        /// </summary>
        public static string SetParameter {
            get {
                return ResourceManager.GetString("SetParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetProductData4Formula.
        /// </summary>
        public static string SetProductData4Formula {
            get {
                return ResourceManager.GetString("SetProductData4Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetProductData4MR.
        /// </summary>
        public static string SetProductData4MR {
            get {
                return ResourceManager.GetString("SetProductData4MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetProductData4Object.
        /// </summary>
        public static string SetProductData4Object {
            get {
                return ResourceManager.GetString("SetProductData4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetQualityData.
        /// </summary>
        public static string SetQualityData {
            get {
                return ResourceManager.GetString("SetQualityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscribeAllBasicEvents.
        /// </summary>
        public static string SubscribeAllBasicEvents {
            get {
                return ResourceManager.GetString("SubscribeAllBasicEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscribeEvent.
        /// </summary>
        public static string SubscribeEvent {
            get {
                return ResourceManager.GetString("SubscribeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferData2PH.
        /// </summary>
        public static string TransferData2PH {
            get {
                return ResourceManager.GetString("TransferData2PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAdvise4Object.
        /// </summary>
        public static string UnAdvise4Object {
            get {
                return ResourceManager.GetString("UnAdvise4Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAdvise4SIS.
        /// </summary>
        public static string UnAdvise4SIS {
            get {
                return ResourceManager.GetString("UnAdvise4SIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAdvise.
        /// </summary>
        public static string UnAdviseFromPCell {
            get {
                return ResourceManager.GetString("UnAdviseFromPCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnChainBatchFromBatch.
        /// </summary>
        public static string UnChainBatchFromBatch {
            get {
                return ResourceManager.GetString("UnChainBatchFromBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnlockObject.
        /// </summary>
        public static string UnlockObject {
            get {
                return ResourceManager.GetString("UnlockObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSubscribeEvent.
        /// </summary>
        public static string UnSubscribeEvent {
            get {
                return ResourceManager.GetString("UnSubscribeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateObject.
        /// </summary>
        public static string ValidateObject {
            get {
                return ResourceManager.GetString("ValidateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard.
        /// </summary>
        public static string Wildcard {
            get {
                return ResourceManager.GetString("Wildcard", resourceCulture);
            }
        }
    }
}
